#pragma once

#include "orderbook/order_book.hpp"
#include "orderbook/trade.hpp"
#include <vector>

namespace hft {

class MatchingEngine {
public:
    // Submit an order: match what we can, then add remainder to the book.
    // Returns all trades generated by this order.
    std::vector<Trade> submitOrder(Order order);

    // Read-only access to the underlying order book
    [[nodiscard]] const OrderBook& book() const { return book_; }

    // Cancel/modify forwarded to the book
    bool cancelOrder(OrderId id) { return book_.cancelOrder(id); }
    bool modifyOrder(OrderId id, Quantity new_qty) {
        return book_.modifyOrder(id, new_qty);
    }

    // Stats
    [[nodiscard]] uint64_t totalTradesGenerated() const { return next_trade_id_ - 1; }

private:
    // Try to match an incoming BUY against the ask side
    std::vector<Trade> matchBuy(Order& incoming);

    // Try to match an incoming SELL against the bid side
    std::vector<Trade> matchSell(Order& incoming);

    OrderBook book_;
    uint64_t  next_trade_id_ = 1;
};

} // namespace hft
